exports.ACTION = 'ACTION';
exports.INITIAL_CACHE  = 'INITIAL_CACHE'
exports.SEARCH_REQUEST = 'SEARCH_REQUEST';
exports.REFRESH_ENTITY = 'REFRESH_ENTITY';
exports.SEARCH_SUCCESS = 'SEARCH_SUCCESS';
exports.SUGGEST_GAME   = 'SUGGEST_GAME';
exports.UNSUGGEST_GAME = 'UNSUGGEST_GAME';